favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4914071
  brandStrength: 0
  lightness: 0.4946294
  brandColors:
    - '#C2D8E3'
    - '#1F1F1F'
    - '#65666A'
    - '#A3ADB6'
    - '#DFB1A6'
  rhythmicContrast: 0.4924812
typography_spectrum: 0.5461869
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2918822562787682
name: Visuals by Najee
