name: Visual Correspondence
favicon: null
layout_spectrum: 0.27281
typography_spectrum: 0.53663
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C2D8E3'
    - '#1F1F1F'
    - '#65666A'
    - '#A3ADB6'
    - '#DFB1A6'
  brandStrength: 0
  lightness: 0.4946294
  saturation: 0.3125
  rhythmicContrast: 0.4924812
purpose: []
