analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.27281
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3125
  brandStrength: 0
  rhythmicContrast: 0.4924812
  brandColors:
    - '#C2D8E3'
    - '#1F1F1F'
    - '#65666A'
    - '#A3ADB6'
    - '#DFB1A6'
  lightness: 0.4946294
purpose: []
favicon: null
name: Visual Correspondence
typography_spectrum: 0.53663
