analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4183673
  brandStrength: 0.6299677
  lightness: 0.5247046
  brandColors:
    - '#EFEFEF'
    - '#222222'
    - '#5D6A73'
    - '#98AAB8'
    - '#804245'
  rhythmicContrast: 0.604189
typography_spectrum: 0.5461869
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2918822562787682
favicon: null
name: Visuals by Najee
